baseURL: "https://theuselessweb.com/sites"
languageCode: en-us
title: "The useless web Archive"
paginate: 100
paginatePath: ''
permalinks:
  sites: /:slug
markup:
  goldmark:
    renderer:
      unsafe: true
